# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright © 2024 Erez Geva <ErezGeva2@gmail.com>
#
# @author Erez Geva <ErezGeva2@@gmail.com>
# @copyright © 2024 Erez Geva
#
# GitHub ABI compare
###############################################################################

name: ABI

# Start manually
on: workflow_dispatch

env:
  USER: builder

jobs:
  abi:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/deb.trixie:latest

    steps:

    - name: checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: continuous integration
      run: |
        chown -R $USER:$USER .
        su $USER -c tools/ci_abi.sh

    - name: save ABI compare report
      uses: actions/upload-artifact@v4
      with:
        name: abi_report
        retention-days: 90
        path: compat_reports/
