# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright © 2023 Erez Geva <ErezGeva2@gmail.com>
#
# @author Erez Geva <ErezGeva2@@gmail.com>
# @copyright © 2023 Erez Geva
#
# GitHub Continuous Integration script
###############################################################################

name: continuous integration

# On evry push and Pull Request (PR)
on: [push, pull_request]
env:
  USER: builder

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        names: [deb.trixie, deb.bookworm, rpmbuild, pacmanbuild, portage]
      fail-fast: false
    container:
      image: ghcr.io/${{ github.repository_owner }}/${{ matrix.names }}:latest
    env:
      GITHUB_CONTAINER: ${{ matrix.names }}

    steps:

    - name: checkout repository
      uses: actions/checkout@v3

    - name: continuous integration
      run: |
        case "$GITHUB_CONTAINER" in
          deb.*)
            # Debian place the debian packages in the parent folder
            chown -R $USER:$USER ..
            ;;
          *)
            chown -R $USER:$USER .
            ;;
        esac
        su $USER -c tools/ci.sh

  cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        names: [deb.trixie, deb.bookworm]
      fail-fast: false
    container:
      image: ghcr.io/${{ github.repository_owner }}/${{ matrix.names }}:latest

    steps:

    - name: checkout repository
      uses: actions/checkout@v3

    - name: cross build
      run: |
        chown -R $USER:$USER ..
        su $USER -c "make deb_arc arm64"

  pkgs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        names: [deb.trixie, deb.bookworm, rpmbuild, pacmanbuild]
      fail-fast: false
    container:
      image: ghcr.io/${{ github.repository_owner }}/${{ matrix.names }}:latest
    env:
      GITHUB_CONTAINER: ${{ matrix.names }}

    steps:

    - name: checkout linuxptp repository
      uses: actions/checkout@v3
      with:
        repository: nwtime/linuxptp
        path: linuxptp

    - name: checkout repository
      uses: actions/checkout@v3
      with:
        path: libptpmgmt

    - name: test with linuxptp
      run: |
        chown -R $USER:$USER .
        su $USER -c libptpmgmt/tools/github_build.sh
        libptpmgmt/tools/github_pkgs.sh

  mem:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        names: [utest_address, utest_valgrid]
      fail-fast: false
    container:
      image: ghcr.io/${{ github.repository_owner }}/deb.trixie:latest
    env:
      GITHUB_TOOL: ${{ matrix.names }}

    steps:

    - name: checkout repository
      uses: actions/checkout@v3

    - name: unit test with memory check
      run: |
        chown -R $USER:$USER .
        su $USER -c "tools/$GITHUB_TOOL.sh -c"
