# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright © 2023 Erez Geva <ErezGeva2@gmail.com>
#
# @author Erez Geva <ErezGeva2@@gmail.com>
# @copyright © 2023 Erez Geva
#
# GitHub Continuous Integration script
###############################################################################

name: continuous integration

# On evry push and Pull Request (PR)
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        names: [deb.trixie, deb.bookworm, deb.bullseye,
                rpmbuild, pacmanbuild, portage]
      fail-fast: false
    container:
      image: ghcr.io/${{ github.repository_owner }}/${{ matrix.names }}:latest
    env:
      USER: builder
      GITHUB_CONTAINER: ${{ matrix.names }}

    steps:

    - name: checkout repository
      uses: actions/checkout@v3

    - name: continuous integration
      run: |
        case "$GITHUB_CONTAINER" in
          portage)
            # Gentoo sudo require password, better to stay with root user
            tools/ci.sh
            ;;
          deb.*)
            # Debian place the debian packages in the parent folder
            chown -R $USER:$USER ..
            su $USER -c tools/ci.sh
            ;;
          *)
            chown -R $USER:$USER .
            su $USER -c tools/ci.sh
            ;;
        esac

  mem:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        names: [utest_address, utest_valgrid]
      fail-fast: false
    container:
      image: ghcr.io/${{ github.repository_owner }}/deb.trixie:latest
    env:
      GITHUB_TOOL: ${{ matrix.names }}

    steps:

    - name: checkout repository
      uses: actions/checkout@v3

    - name: unit test with memory check
      run: tools/$GITHUB_TOOL.sh -c
